jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      dev:
        - db-dev
    include:
      - db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(kGXTSlfxUWNbRoGuBwNRTJBETjMz04AChYMrwDeY3Cs=)
    password: ENC(/hOuHdVpOgyzKrlqyayORlsTFpIrwe7RYnfAqXEFzIk=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Redis
  data:
    redis:
      host: ENC(GUuFDW7HjE98e7N28Vkb/xoIEgLeOCb5)
      port: 6379
      duration: 600
  config:
    import: vault://
  cloud:
    vault:
      host: 43.200.201.142
      port: 8200
      uri: http://43.200.201.142:8200
      authentication: TOKEN
      token: hvs.SdEQtUjhGCUvZXaEO43yf5id  # Vault Root Token
      kv:
        enabled: true
        backend: secret

email.send: ENC(kGXTSlfxUWNbRoGuBwNRTJBETjMz04AChYMrwDeY3Cs=)

springdoc:
  default-consumes-media-type: application/json # ?? ??? ??
  default-produces-media-type: application/json # ?? ??? ??
  swagger-ui:
    operations-sorter: method # operations ?? ??? HTTP Method ?
    tags-sorter: alpha # tag ?? ??? ??? ?
    #path: "swagger.html" # http://localhost:8080/swagger.html? ?? ??
    path: "/" # http://localhost:8080? ?? ??
