jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasypt.encryptor.password}

spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      dev:
        - db-dev
    include:
      - db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(kGXTSlfxUWNbRoGuBwNRTJBETjMz04AChYMrwDeY3Cs=)
    password: ENC(/hOuHdVpOgyzKrlqyayORlsTFpIrwe7RYnfAqXEFzIk=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Redis
  data:
    redis:
      host: ENC(GUuFDW7HjE98e7N28Vkb/xoIEgLeOCb5)
      port: 6379
      duration: 600

#oauth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: ENC(1c6jtMDIU7/ZloQv+k1W9YP6arHGBdguKmwtI4tU1dHAA0iYyK6pogIBiRzUp5V6)
            client_secret: ENC(Z+CSlGFc9ux+mvN1t2c3mWoKv8sqoJF5gE+UoJTMHD8YZRYtOyO4WOJ9Qz7xi97E)
            redirect_uri: ENC(SvHz8bAglAd/vqUrE2NAlhyfEJ1klhK0pCEq9dfQLqCPKxG8gZjjAmYd+HXakhjjd+SxflkXRt8=)
            scope:
              - name
              - email
              - profile_image
            authorization_grant_type: authorization_code
            client_name: Kakao
            client_authentication_method: post
            provider: kakao
          #        google:
          #          client-id: YOUR_GOOGLE_CLIENT_ID
          #          client-secret: YOUR_GOOGLE_CLIENT_SECRET
          #          redirect-uri: "{baseUrl}/login/oauth2/code/google"
          #          scope:
          #            - profile
          #            - email
          #          authorization-grant-type: authorization_code
          #          client-name: Google
          #          client-authentication-method: post
          #          provider: google
          #
          #        naver:
          #          client-id: YOUR_NAVER_CLIENT_ID
          #          client-secret: YOUR_NAVER_CLIENT_SECRET
          #          redirect-uri: "{baseUrl}/login/oauth2/code/naver"
          #          scope:
          #            - name
          #            - email
          #            - profile_image
          #          authorization-grant-type: authorization_code
          #          client-name: Naver
          #          client-authentication-method: post
          #          provider: naver


        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user_info_uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          #        naver:
          #          authorization-uri: <https://nid.naver.com/oauth2.0/authorize>
          #          token-uri: <https://nid.naver.com/oauth2.0/token>
          #          user-info-uri: <https://openapi.naver.com/v1/nid/me>
          #          user-name-attribute: response
          #        google:
          #          authorization-uri: <https://accounts.google.com/o/oauth2/auth>
          #          token-uri: <https://oauth2.googleapis.com/token>
          #          user-info-uri: <https://www.googleapis.com/oauth2/v3/userinfo>
          #          user-name-attribute: sub

email.send: ENC(kGXTSlfxUWNbRoGuBwNRTJBETjMz04AChYMrwDeY3Cs=)
email.send: ${email.send}

springdoc:
  default-consumes-media-type: application/json # ?? ??? ??
  default-produces-media-type: application/json # ?? ??? ??
  swagger-ui:
    operations-sorter: method # operations ?? ??? HTTP Method ?
    tags-sorter: alpha # tag ?? ??? ??? ?
    #path: "swagger.html" # http://localhost:8080/swagger.html? ?? ??
    path: "/" # http://localhost:8080? ?? ??
