jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${jasypt.encryptor.password}

spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      dev:
        - db-dev
    include:
      - db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(kGXTSlfxUWNbRoGuBwNRTJBETjMz04AChYMrwDeY3Cs=)
    password: ENC(/hOuHdVpOgyzKrlqyayORlsTFpIrwe7RYnfAqXEFzIk=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Redis
  data:
    redis:
      host: ENC(GUuFDW7HjE98e7N28Vkb/xoIEgLeOCb5)
      port: 6379
      duration: 600

  #oauth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: ${kakao.client.id}
            client_secret: ${kakao.client.secret}
            redirect_uri: http://localhost:8080/auth/kakao/callback
            scope:
              - name
              - email
              - profile_image
            authorization_grant_type: authorization_code
            client_name: Kakao
            client_authentication_method: post
            provider: kakao

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user_info_uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

email.send: ${email.send}

springdoc:
  default-consumes-media-type: application/json # ?? ??? ??
  default-produces-media-type: application/json # ?? ??? ??
  swagger-ui:
    operations-sorter: method # operations ?? ??? HTTP Method ?
    tags-sorter: alpha # tag ?? ??? ??? ?
    #path: "swagger.html" # http://localhost:8080/swagger.html? ?? ??
    path: "/" # http://localhost:8080? ?? ??
